CREATE TABLE
    WS_IP_PORT
    (
        DOMAIN_CODE VARCHAR(32) NOT NULL,
        ORG_CODE VARCHAR(32) NOT NULL,
        SERV_ADDR VARCHAR(64),
        NOTE VARCHAR(64),
        USE_STATUS VARCHAR(1),
        CONSTRAINT PK_FA PRIMARY KEY (DOMAIN_CODE, ORG_CODE)
    );
COMMENT ON TABLE WS_IP_PORT
IS
    '服务地址表';
COMMENT ON COLUMN WS_IP_PORT.DOMAIN_CODE
IS
    '业务域code';
COMMENT ON COLUMN WS_IP_PORT.ORG_CODE
IS
    '单位编码';
COMMENT ON COLUMN WS_IP_PORT.SERV_ADDR
IS
    '服务地址';
COMMENT ON COLUMN WS_IP_PORT.NOTE
IS
    '备注';
COMMENT ON COLUMN WS_IP_PORT.USE_STATUS
IS
    '是否启用';