CREATE TABLE
    WS_SEND_RECORD
    (
        SEND_RECORD_ID VARCHAR(64) NOT NULL,
        ORG_CODE VARCHAR(12),
        DOMAIN_CODE VARCHAR(8),
        BEAN_ID VARCHAR(128),
        PARAM_STR CLOB,
        SEND_COUNT VARCHAR(100),
        SEND_STATUS SMALLINT,
        SEND_TIME TIMESTAMP,
        PRIMARY KEY (SEND_RECORD_ID)
    );
COMMENT ON TABLE WS_SEND_RECORD
IS
    '远程调用发送数据表';
COMMENT ON COLUMN WS_SEND_RECORD.SEND_RECORD_ID
IS
    '发送数据主键id';
COMMENT ON COLUMN WS_SEND_RECORD.ORG_CODE
IS
    '组织机构编码';
COMMENT ON COLUMN WS_SEND_RECORD.DOMAIN_CODE
IS
    '业务域编码';
COMMENT ON COLUMN WS_SEND_RECORD.BEAN_ID
IS
    '业务beanid';
COMMENT ON COLUMN WS_SEND_RECORD.PARAM_STR
IS
    '转换成的字符串的参数信息';
COMMENT ON COLUMN WS_SEND_RECORD.SEND_COUNT
IS
    '发送次数';
COMMENT ON COLUMN WS_SEND_RECORD.SEND_STATUS
IS
    '发送状态（0：未成功；1：已成功；2：发送锁定中）';
COMMENT ON COLUMN WS_SEND_RECORD.SEND_TIME
IS
    '发送时间';
