
INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('402897814eceb153014eceb174870001', 'qqqqqq', '供应商一', '山东', 'sss', 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('402897814eceb153014eceb1d0a40002', 'wwwww', '供应商二', '河北', '', 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('402897814eceb153014eceb231730003', 'eeeee', '供应商三', '湖南', '', 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20610001', '20610001', '陕西中烟工业公司', '陕西', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20520001', '20520001', '贵州中烟工业公司', '贵州', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20510001', '20510001', '川渝中烟工业公司', '四川', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20450001', '20450001', '广西中烟工业公司', '广西', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20430001', '20430001', '湖南中烟工业公司', '湖南', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20420001', '20420001', '湖北中烟工业公司', '湖北', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20410001', '20410001', '河南中烟工业公司', '河南', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20370001', '20370001', '山东中烟工业公司', '山东', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20360001', '20360001', '江西中烟工业公司', '江西', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20350001', '20350001', '福建中烟工业公司', '福建', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20340001', '20340001', '安徽中烟工业公司', '安徽', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20330001', '20330001', '浙江中烟工业公司', '浙江', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20320001', '20320001', '江苏中烟工业公司', '江苏', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('20130001', '20130001', '河北中烟工业公司', '河北', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('12530401', '12530401', '红塔集团', '云南', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('12530104', '12530104', '红云红河烟草(集团)有限责任公司', '云南', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('10310001', '10310001', '上海烟草集团有限责任公司', '上海', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('99000002', '99000002', '中国烟草实业发展中心', '中国', NULL, 1, NULL, NULL, '0');

INSERT INTO db2admin.T_C_BS_SUPPLY (SUPPLY_UUID, SUPPLY_CODE, SUPPLY_NAME, AREA, MEMO, IS_ACTIVE, REMOTE_ORG_CODE, SYNC_TIME, SYNC_STATUS)
VALUES ('99999991', '99999991', '其他', '110000', '99999991', 1, NULL, NULL, '0');
